"""Streaming configuration."""

from src.config import EVENTS_DIR, WAREHOUSE_PATH

EVENT_STREAM_PATH = EVENTS_DIR / "event_stream.jsonl"
PRODUCER_INTERVAL_SECONDS = 1
CONSUMER_POLL_INTERVAL_SECONDS = 0.5
METRICS_WINDOW_MINUTES = 5
WAREHOUSE_DB = WAREHOUSE_PATH
